spring.application.name=emandi-backend
# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Database Configuration (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:emandicorp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
jwt.secret=3c20eb6949d871f4ea8f7227d9c789091a75cd4415fb92ea9c38b4523c662298
jwt.expiration=3600000



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.emandi.backend=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=26aayush2006@gmail.com
spring.mail.password=jaek yuju huzm ffza   # Not your Gmail password, use App Password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
